#Arreglos y clases
## Matrices
Una matriz es un arreglo de mxn elementos

 \begin{bmatrix}
    a_{11} & a_{12} & \cdots & a_{1n} \\
    a_{21} & a_{22} & \cdots & a_{2n} \\
    \vdots & \vdots & \ddots & \vdots \\
    a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}


In [6]:
A=[[1,2,3], [4,5,6], [7,8,9]]
print (A)
type(A)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


list

In [12]:
#Vamos a crear otra
B=[[21,34,40],[71,17,77],[73,81,28]]
print(B)
A+B


[[21, 34, 40], [71, 17, 77], [73, 81, 28]]


[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
2*A

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [20]:
A[0][0]
#A[0,0]



1

##Vectores y Listas

In [25]:
L=A[0]
M=B[0]


In [27]:
a=L[0]
b=M[0]
a+b

22

In [29]:
a==1
#Resultado booleano: (true o false)

True

###Suma de "vectores"

In [31]:
len(L)==len(M)

True

In [33]:
suma=[L[0]+M[0],L[1]+M[1],L[2]+M[2]]
suma

[22, 36, 43]

In [34]:
suma=[L[i]+M[i] for i in range(3)]

#Creación de funciones globales
La función para crear funciones es `def` que se cierra con un debug (`print` o `return`)

In [37]:
 #Es como una funcion static o void
 def hola():
  print("Hola, me llamo Cesar")

In [38]:
hola()

Hola, me llamo Cesar


In [45]:
#declaras la funcion static
def saludar(s,n):
  print(f"Hola, me llamo {s} y tengo {n} años")

In [65]:
saludar("Cesar", 18)

Hola, me llamo Cesar y tengo 18 años


In [72]:
def par (x):
  for x in range(10):
    if x%2==0:
      print(f"{x} es par")
    else:
      print(f"{x} es impar")

In [74]:
par(7)

0 es par
1 es impar
2 es par
3 es impar
4 es par
5 es impar
6 es par
7 es impar
8 es par
9 es impar


In [75]:
def suma_vectorial (L,M):
  x= [L[i]+M[i] for i in range(len(L))]
  return x

In [78]:
L=[1,2,3]
M=[21,34,40]
suma_vectorial(L,M)

[22, 36, 43]

##Módulos o librerías

In [79]:
#el asterisco muestra todos los elementos de la librería, from math import *
import math
from math import sqrt, pi

In [80]:
sqrt(68)

8.246211251235321

In [81]:
pi

3.141592653589793

#El módulo NumPy
La función `array`

In [82]:
#La función array es un convertidor, convierte una lista en un vector
import numpy as np

L_vector= np.array(L)
M_vector= np.array(M)

L_vector+M_vector

array([22, 36, 43])

In [86]:
#Se escriben las matrices de la siguiente manera y posteriormente se usa el.reshape para comodar la matriz segun la cantidad de filas y columnas
C=[9,2,2,2,3,3,2,17,2]
A=[8,1,1,1,2,2,1,16,1]

C_matriz=np.array(C).reshape(3,3)
A_matriz=np.array(A).reshape(3,3)
print(C_matriz)
print(A_matriz)

[[ 9  2  2]
 [ 2  3  3]
 [ 2 17  2]]
[[ 8  1  1]
 [ 1  2  2]
 [ 1 16  1]]


In [87]:
#El @ sirve para hacer multiplicación
C_matriz @ A_matriz

array([[76, 45, 15],
       [22, 56, 11],
       [35, 68, 38]])

In [88]:
#Al no ser conmutativas se hacen las dos operaciones
A_matriz @ C_matriz

array([[76, 36, 21],
       [17, 42, 12],
       [43, 67, 52]])